### PR TITLE
For krahjohlito

### PR DESCRIPTION
**Pull request by rickgaiser**
This is more how I think it "should" be, but it's **not** working.

Just like the original function, I'm now using `((u32 *)sfxData->buffer)[3]`, so 4 bytes, starting at position 12.

I don't know what should be at that location, becouse I cannot find the proper headers for this type of ADPCM files.

Anyway, the value is 0 for most files, so that's strange. As a workaround I'm calculating the duration based on the filesize, but this will be problematic, becouse the compression ratio is not fixed.

So.... do you know what sort of headers these files have, and how to calculate the exact duration?

The duration of the fading animation I've also calculated, BUT, we don't know if we're using 50 of 60 fps. The fps will actually make the anomation faster or slower, lol. So in ntsc areas people will have a 20% faster animation. This could be fixed 2 ways:
1 - The animation duration should not depend on FPS, but on time.
2 - We can add a function to renderman to ask for the fps

And lastly, the **Delayed** change does not look right. I think it was part of another change to gsKit a long time ago that I reverted. So thanks, I'll remove it from the ifcaro PR but I've added a revert in this PR.

### CODE REVIEW

**Comment by KrahJohlito** [comment]
The ‘real’ converter from the sdk leaves that part of the header reserved, so 0
https://github.com/ps2dev/ps2sdk/blob/master/tools/adpenc/src/main.c#L142

It was a modified version distributed for the purpose of use with OPL that writes the decompressed size in there header
https://www.psx-place.com/threads/wav-to-adp-converter-for-opl.21568/

I can’t remember cause it was a while ago but it’s possible the default sounds were converted with the original converter since at the time I didn’t expect to be reading additional data from the header of the default sounds, that’s why the delay was hardcoded to 1200.... not very well thought out.. 

On the plus side I should be able to get access to the original wav files and update them in the repo.

Gah.. didn’t think about FPS.. I like the idea of option 1 to have the animation based on time.

**Comment by rickgaiser** [comment]
> The ‘real’ converter from the sdk leaves that part of the header reserved, so 0
> https://github.com/ps2dev/ps2sdk/blob/master/tools/adpenc/src/main.c#L142
> 
> It was a modified version distributed for the purpose of use with OPL that writes the decompressed size in there header
> https://www.psx-place.com/threads/wav-to-adp-converter-for-opl.21568/
> 
I didn't know it existed, nice. Can you make a PR to ps2sdk with this change? I think it's ok to use this field for this purpose permanently.

> I can’t remember cause it was a while ago but it’s possible the default sounds were converted with the original converter since at the time I didn’t expect to be reading additional data from the header of the default sounds, that’s why the delay was hardcoded to 1200.... not very well thought out..
> 
> On the plus side I should be able to get access to the original wav files and update them in the repo.
> 
Only 1 has something in that field. The rest has 0. If you can update those files in OPL, and send the PR to ps2sdk, then we will know the exact length of all files in the future.

> Gah.. didn’t think about FPS.. I like the idea of option 1 to have the animation based on time.

Yes, me too. That's how all games are rendered.

Unfortunately I don't have any spare time left. I think we must focus on fixing the exit issue so the newlib PR can get merged. All these sound and animation improvement can be added later on.

**Comment by KrahJohlito** [comment]
@rickgaiser I thought the exit issue was fixed by removing the delay from sysExit?

**Comment by rickgaiser** [comment]
The exit worked when I removed the delay or any other **random** part of the exit that consumes time. So I don't this this the delay is the real issue, but we can use it as a workaround.

Why you ask? Is it still freezing on exit?

**Comment by KrahJohlito** [comment]
> I think we must focus on fixing the exit issue so the newlib PR can get merged
I haven’t tested exit recently just asking because of your comment here.

Also elpatas messaged me saying it froze on logo first then exit for him, I will try test later

**Pull request merged**
